on:
  push:
    branches: [ main ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/list-repository-languages@main
        id: list-languages
      - name: Check if Python
        if: contains(fromJSON(steps.list-languages.outputs.languages), 'Javascript')
        run: echo "This repository contains Python code."
