name: Matrix Language Jobs
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/list-repository-languages@main
        id: list-languages
    outputs:
      languages: ${{ steps.list-languages.outputs.languages }}

  python-action:
    needs: [run]
    runs-on: ubuntu-latest
    if: contains(fromJSON(needs.run.outputs.languages), 'Python')
    steps:       
    # Checks-out the repository so our job can access it
      - uses: actions/checkout@v2
      - name: Install pip detect-secrets
        run: |
          pip install bandit
      - name: Scan SAST repository for python
        run: |
          # scripts to scan repository for new secrets
          bandit -r ${{ github.workspace }} -f json -o python-SAST.json --exit-zero
     # Upload Artifacts
      - name: Upload the SST scan output
        uses: actions/upload-artifact@v2
        with:
          name: scan_results
          path: python-SAST.json
