version: 0.2
on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:
  
phases:
  install:
    runtime-versions:
      java: openjdk17
      docker: 20
    commands:
      - apt-get update
      - apt-get install -y maven
      - wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.2.1/dependency-check-7.2.1-release.zip -O dependency-check.zip
      - unzip dependency-check.zip
      - rm dependency-check.zip
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip -O sonar-scanner.zip
      - unzip sonar-scanner.zip
      - rm sonar-scanner.zip
      - wget https://github.com/aquasecurity/trivy/releases/download/v0.20.0/trivy_0.20.0_Linux-64bit.deb -O trivy.deb
      - dpkg -i trivy.deb
      - rm trivy.deb
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_Linux.tar.gz -O zap.tar.gz
      - tar -xvf zap.tar.gz
      - rm zap.tar.gz

  pre_build:
    commands:
      - mvn clean install
      - ./dependency-check/bin/dependency-check.sh --project "My Project" --scan ./target/*.jar --format HTML --out ./dependency-check-report.html
      - ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner -Dsonar.projectKey=my-project -Dsonar.sources=. -Dsonar.host.url=https://sonarqube.example.com -Dsonar.login=YOUR_SONAR_LOGIN_TOKEN
      - mvn license:check

  build:
    commands:
      - docker build -t my-image .
      - trivy image --exit-code 1 --no-progress my-image
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY
      - docker tag my-image:latest $ECR_REPOSITORY:latest
      - docker push $ECR_REPOSITORY:latest

  post_build:
    commands:
      - ./zap/zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true
      - ./zap/zap-api-scan.py -t https://example.com/api -f openapi -r zap-report.html
      - aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER
      - kubectl apply -f deployment.yml
      - kubectl apply -f service.yml
      - aws s3 cp dependency-check-report.html s3://$S3_BUCKET/dependency-check-report.html
      - aws s3 cp zap-report.html s3://$S3_BUCKET/zap-report.html
