name: Python security workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codeql-analysis:
    name: CodeQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  trufflehog-scan:
    name: Trufflehog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install trufflehog
        run: pip install trufflehog
      - name: Scan for secrets
        run: trufflehog --regex --entropy=False . > secrets.txt
      - name: Upload secrets report
        uses: actions/upload-artifact@v2
        with:
          name: secrets
          path: secrets.txt
