name: SAST
on:
  push:
    branches: [ main ]
jobs:
  sast:
    runs-on: ubuntu-latest
    continue-on-error: true
    # Steps define the order in which the tasks will be executed
    steps:
       # Checks-out the repository so our job can access it
      - uses: actions/checkout@v2
      - name: Install pip detect-secrets
        run: |
          pip install bandit
      - name: Scan SAST repository for python
        run: |
          # scripts to scan repository for new secrets
          bandit -r ${{ github.workspace }} -f json -o python-SAST.json --exit-zero
     # Upload Artifacts
      - name: Upload the SST scan output
        uses: actions/upload-artifact@v2
        with:
          name: scan_results
          path: python-SAST.json
