# This is our basic workflow for automating secrets scanning with GitHub Actions

name: Detect-secrets Secrets Scanning
# Controls when the workflow will run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '00 05 * * *' #daily scan at 05:00 AM

jobs:
 # This workflow contains a single job called "Scan-for-secrets"
 Scan-for-secrets:
   # The type of runner that the job will run on
   runs-on: ubuntu-latest
   # Steps define the order in which the tasks will be executed
   steps:
     # Checks-out the repository so our job can access it
     - uses: actions/checkout@v2
     # Installs secret scanner on the runner
     - name: Install detect-secrets
       run: sudo pip install detect-secrets
     # Scan repo for secrets
     - name: Run scanner for the repository
       run: |
        detect-secrets -C ${{ github.workspace }} scan > scan_output.json
     # Upload Artifacts
     - name: Upload the scan output
       uses: actions/upload-artifact@v2
       with:
         name: scan_results
         path: scan_output.json

