# File: .github/workflows/secret_scanning.yml
name: Secret Scanning
on: push
jobs:
  scan-secrets:
    name: Scanning for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Create an initial .secrets.baseline if .secrets.baseline does not exist
        run: |
          if [ ! -f .secrets.baseline ]; then
            # This generated baseline file will only be temporarily available on the GitHub side and will not appear in the user's local files.
            # Scanning an empty folder to generate an initial .secrets.baseline without secrets in the results.
            echo "⚠️ No existing .secrets.baseline file detected. Creating a new blank baseline file."
            mkdir empty-dir
            detect-secrets scan empty-dir > .secrets.baseline
            echo "✅ Blank .secrets.baseline file created successfully."
            rm -r empty-dir
          else
            echo "✅ Existing .secrets.baseline file detected. No new baseline file will be created."
          fi
        
      - name: Secret Scanner
        uses: secret-scanner/action@0.2.1
        with:
          # Optional: The path to the directory containing the files to exclude from secret scanning
          exclude_files_path: '.github/actions/secret-scanner'
          # Optional: Additional arguments to pass to detect-secrets
          detect_secret_additional_args: '--no-verify --exclude-files .secrets.baseline'
          # Optional: Enable push protection to block pushes that contain high-confidence secrets
          push_protection: true
