on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '00 05 * * *' #daily scan at 05:00 AM

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install trufflehog Secret Scanning 
      run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
    - name: Secret Scanning 
      run: |
          trufflehog filesystem ${{ github.workspace }} -j > trufflehog-result.json
    - name: Upload whispers scan output
      uses: actions/upload-artifact@v2
      with:
        name: trufflehog-result
        path: trufflehog-result.json

