name: 'detect-secrets Action'
#description: 'Scans your GitHub repository for accidentally committed secrets, enhances code security, and aids in secret cleanup.'
#branding:
#  icon: 'alert-octagon'
#  color: 'red'
  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  secret-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pip detect-secrets
        run: |
          pip install detect-secrets
          
      - name: Create an initial .secrets.baseline if .secrets.baseline does not exist
        run: |
          if [ ! -f .secrets.baseline ]; then
            # This generated baseline file will only be temporarily available on the GitHub side and will not appear in the user's local files.
            # Scanning an empty folder to generate an initial .secrets.baseline without secrets in the results.
            echo "⚠️ No existing .secrets.baseline file detected. Creating a new blank baseline file."
            mkdir empty-dir
            detect-secrets scan empty-dir > .secrets.baseline
            echo "✅ Blank .secrets.baseline file created successfully."
            rm -r empty-dir
          else
            echo "✅ Existing .secrets.baseline file detected. No new baseline file will be created."
          fi

      - name: Scan repository for secrets
        id: save_output
        run: |
          # scripts to scan repository for new secrets
          
          # backup the list of known secrets
          cp .secrets.baseline .secrets.new

          # find the secrets in the repository
          detect-secrets scan --baseline .secrets.new --exclude-files '.secrets.*' --exclude-files '.git*' --json > .secrets.result
          echo $(cat .secrets.result)
          
          # export the result of the scan as an artifact
          echo "✅ Scan completed. Exporting the result as an artifact."
          echo "The output is ${{ steps.save_output.outputs.files }}"

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: secrets-result
          path: .secrets.result
          if-no-files-found: warn

          
