on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: filesystem --json trufflehog-result.json
      # Upload Artifacts
    - name: Upload whispers scan output
      uses: actions/upload-artifact@v2
      with:
        name: trufflehog-result
        path: trufflehog-result.json
